"""Device data and explicit model assumptions for the Ag/PVA/Pt model."""

DEVICE_THICKNESS = 100e-9
TEMPERATURE_K = 300.0

# Literature/device reference values. These are comparison targets, not model inputs.
LITERATURE_SET_VOLTAGE = 0.27
LITERATURE_RESET_VOLTAGE = -0.13
LITERATURE_ON_RESISTANCE_OHM = 1e3
LITERATURE_OFF_RESISTANCE_OHM = 1e5

SET_VOLTAGE = LITERATURE_SET_VOLTAGE
RESET_VOLTAGE = LITERATURE_RESET_VOLTAGE

# Simulation assumptions/calibration parameters. These are not measured PVA data.
AG_ION_MOBILITY_M2_V_S = 5e-13
ACTIVATION_ENERGY_EV = 0.20
BOLTZMANN_EV_K = 8.617333262e-5
REFERENCE_TEMPERATURE_K = 300.0
TIME_STEP_S = 1e-3
POSITIVE_BIAS_TIME_LIMIT_S = 0.30
AVAILABLE_ION_FRACTION = 1.0

AG_RESISTIVITY_OHM_M = 1.6e-8
INITIAL_FILAMENT_RADIUS_M = 0.1e-9
MAX_FILAMENT_RADIUS_M = 0.5e-9
GAP_RESISTANCE_SCALE_OHM = LITERATURE_OFF_RESISTANCE_OHM
DISSOLUTION_RATE_FACTOR = 1.5

AREA = 5e-6 * 5e-6

MAX_SWEEP_VOLTAGE = 0.5
MIN_SWEEP_VOLTAGE = -0.5
